notifications:
  email: false
sudo: required
language: node_js
dist: trusty
node_js:
  - stable
addons:
 chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli@0.4.x
install:
  - npm install
script:
  - npm run build
  - npm run bundlesize
after_success:
  - lhci autorun
